-- ######################################################################
-- # FINANCEDB - SCRIPT DE CREACIÓN DE ESQUEMA (ORACLE 21c)
-- # OBJETIVO: Idempotencia, Orden y Consistencia.
-- ######################################################################

-- ======================================================================
-- 1. LIMPIEZA TOTAL: Eliminar Objetos Existentes para Idempotencia
--    El orden es crucial: Tablas antes que Secuencias.
-- ======================================================================

-- 1.1. Eliminar Tablas
-- Se usa BEGIN...END con EXCEPTION para ignorar errores si el objeto no existe,
-- asegurando que el script no falle en la primera ejecución.

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE TRANSACTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE BUDGETS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE CATEGORIES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE ACCOUNTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE EXTERNAL_DEBTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE SAVINGS_GOALS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE NOTIFICATIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 1.2. Eliminar Secuencias
BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE USER_ID_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE ACC_ID_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE CAT_ID_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE BUD_ID_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE TRX_ID_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE EXT_ID_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE SVG_ID_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP SEQUENCE NOT_ID_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ======================================================================
-- 2. CREACIÓN DE SECUENCIAS (Sustituto de AUTO_INCREMENT)
-- ======================================================================

CREATE SEQUENCE USER_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ACC_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CAT_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BUD_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TRX_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EXT_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SVG_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE NOT_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- ======================================================================
-- 3. CREACIÓN DE TABLAS
-- ======================================================================

-- 1. USERS
CREATE TABLE USERS (
                       ID NUMBER PRIMARY KEY,
                       FIRST_NAME VARCHAR2(100) NOT NULL,
                       LAST_NAME VARCHAR2(100),
                       EMAIL VARCHAR2(100) NOT NULL UNIQUE,
                       USERNAME VARCHAR2(100) NOT NULL UNIQUE,
                       PASSWORD_HASH VARCHAR2(255) NOT NULL,
                       ROLE VARCHAR2(20) NOT NULL CHECK (ROLE IN ('USER', 'ADMIN')),
                       CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. ACCOUNTS
CREATE TABLE ACCOUNTS (
                          ID NUMBER PRIMARY KEY,
                          USER_ID NUMBER NOT NULL,
                          NAME VARCHAR2(100) NOT NULL,
                          TYPE VARCHAR2(20) NOT NULL CHECK (TYPE IN ('DEBITO', 'CREDITO')),
                          BANK_NAME VARCHAR2(100),
                          INITIAL_BALANCE NUMBER(12, 2) DEFAULT 0.00 NOT NULL,
                          CLOSING_DATE NUMBER(2),
                          PAYMENT_DATE NUMBER(2),
                          IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0, 1))
);

-- 3. CATEGORIES
CREATE TABLE CATEGORIES (
                            ID NUMBER PRIMARY KEY,
                            USER_ID NUMBER NOT NULL,
                            NAME VARCHAR2(100) NOT NULL,
                            TYPE VARCHAR2(10) NOT NULL CHECK (TYPE IN ('INGRESO', 'GASTO')),
                            MANAGEMENT_TYPE VARCHAR2(20) NOT NULL CHECK (MANAGEMENT_TYPE IN ('PLANIFICADO_MENSUAL', 'DIA_A_DIA'))
);

-- 4. BUDGETS
CREATE TABLE BUDGETS (
                         ID NUMBER PRIMARY KEY,
                         USER_ID NUMBER NOT NULL,
                         CATEGORY_ID NUMBER NOT NULL,
                         AMOUNT NUMBER(12, 2) NOT NULL,
                         MONTH NUMBER(2) NOT NULL,
                         YEAR NUMBER(4) NOT NULL
);

-- 5. TRANSACTIONS
CREATE TABLE TRANSACTIONS (
                              ID NUMBER PRIMARY KEY,
                              USER_ID NUMBER NOT NULL,
                              ACCOUNT_ID NUMBER NOT NULL,
                              CATEGORY_ID NUMBER NULL,
                              TYPE VARCHAR2(20) NOT NULL CHECK (TYPE IN ('INGRESO', 'GASTO', 'TRANSFERENCIA')),
                              AMOUNT NUMBER(12, 2) NOT NULL,
                              DESCRIPTION VARCHAR2(4000),
                              TRANSACTION_DATE DATE DEFAULT SYSDATE NOT NULL, -- Agregamos DEFAULT SYSDATE
                              DESTINATION_ACCOUNT_ID NUMBER NULL
);

-- 6. EXTERNAL_DEBTS
CREATE TABLE EXTERNAL_DEBTS (
                                ID NUMBER PRIMARY KEY,
                                USER_ID NUMBER NOT NULL,
                                NAME VARCHAR2(150) NOT NULL,
                                CREDITOR VARCHAR2(100),
                                TOTAL_AMOUNT NUMBER(12, 2) NOT NULL,
                                CURRENT_BALANCE NUMBER(12, 2) NOT NULL
);

-- 7. SAVINGS_GOALS
CREATE TABLE SAVINGS_GOALS (
                               ID NUMBER PRIMARY KEY,
                               USER_ID NUMBER NOT NULL,
                               NAME VARCHAR2(150) NOT NULL,
                               TARGET_AMOUNT NUMBER(12, 2),
                               CURRENT_AMOUNT NUMBER(12, 2) DEFAULT 0.00 NOT NULL
);

-- 8. NOTIFICATIONS
CREATE TABLE NOTIFICATIONS (
                               ID NUMBER PRIMARY KEY,
                               USER_ID NUMBER NOT NULL,
                               MESSAGE VARCHAR2(255) NOT NULL,
                               IS_READ NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_READ IN (0, 1)),
                               CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


-- ======================================================================
-- 4. CREACIÓN DE FOREIGN KEYS (FKs)
-- ======================================================================

ALTER TABLE ACCOUNTS
    ADD CONSTRAINT FK_ACCOUNT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

ALTER TABLE CATEGORIES
    ADD CONSTRAINT FK_CAT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

ALTER TABLE BUDGETS
    ADD CONSTRAINT FK_BUDGET_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

ALTER TABLE BUDGETS
    ADD CONSTRAINT FK_BUDGET_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID) ON DELETE CASCADE;

ALTER TABLE TRANSACTIONS
    ADD CONSTRAINT FK_TRX_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

ALTER TABLE TRANSACTIONS
    ADD CONSTRAINT FK_TRX_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID);

ALTER TABLE TRANSACTIONS
    ADD CONSTRAINT FK_TRX_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID);

ALTER TABLE TRANSACTIONS
    ADD CONSTRAINT FK_TRX_DEST_ACC FOREIGN KEY (DESTINATION_ACCOUNT_ID) REFERENCES ACCOUNTS (ID);

ALTER TABLE EXTERNAL_DEBTS
    ADD CONSTRAINT FK_EXT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

ALTER TABLE SAVINGS_GOALS
    ADD CONSTRAINT FK_SVG_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

ALTER TABLE NOTIFICATIONS
    ADD CONSTRAINT FK_NOT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

-- ======================================================================
-- 5. FINALIZADO: Cierre de Transacción
-- ======================================================================

COMMIT;

-- Muestra un mensaje de éxito
SELECT 'Script de Base de Datos ORACLE ejecutado y estructura creada exitosamente.' AS STATUS FROM DUAL;