-- ######################################################################
-- # FINANCEDB V2 - ESQUEMA PARA "FINANZAS SLYTHERIN" (ORACLE 21c)
-- # OBJETIVO: Soporte Multi-moneda, Etiquetas y Automatización.
-- ######################################################################

-- ======================================================================
-- 1. LIMPIEZA TOTAL (DROP OBJECTS)
-- ======================================================================



BEGIN
    -- Tablas dependientes (Hijas) primero
    EXECUTE IMMEDIATE 'DROP TABLE TRANSACTION_TAGS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TAGS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RECURRING_TRANSACTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TRANSACTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BUDGETS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CATEGORIES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EXTERNAL_DEBTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SAVINGS_GOALS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE NOTIFICATIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ACCOUNTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Secuencias
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE USER_ID_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE ACC_ID_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE CAT_ID_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE BUD_ID_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE TRX_ID_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE REC_TRX_ID_SEQ'; -- Nueva
    EXECUTE IMMEDIATE 'DROP SEQUENCE TAG_ID_SEQ';     -- Nueva
    EXECUTE IMMEDIATE 'DROP SEQUENCE EXT_ID_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SVG_ID_SEQ';
    EXECUTE IMMEDIATE 'DROP SEQUENCE NOT_ID_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ======================================================================
-- 2. CREACIÓN DE SECUENCIAS
-- ======================================================================

CREATE SEQUENCE USER_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ACC_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CAT_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BUD_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TRX_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE REC_TRX_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE; -- Nueva
CREATE SEQUENCE TAG_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;     -- Nueva
CREATE SEQUENCE EXT_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SVG_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE NOT_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ======================================================================
-- 3. CREACIÓN DE TABLAS
-- ======================================================================

-- 1. USERS (Actualizada HU-03, HU-05)
CREATE TABLE USERS (
                       ID NUMBER PRIMARY KEY,
                       FIRST_NAME VARCHAR2(100) NOT NULL,
                       LAST_NAME VARCHAR2(100),
                       EMAIL VARCHAR2(100) NOT NULL UNIQUE,
                       USERNAME VARCHAR2(100) NOT NULL UNIQUE,
                       PASSWORD_HASH VARCHAR2(255) NOT NULL,
                       ROLE VARCHAR2(20) NOT NULL CHECK (ROLE IN ('USER', 'ADMIN')),
    -- Nuevas preferencias
                       MAIN_CURRENCY VARCHAR2(3) DEFAULT 'PEN' NOT NULL CHECK (MAIN_CURRENCY IN ('PEN', 'USD')),
                       PRIVACY_MODE NUMBER(1) DEFAULT 0 NOT NULL CHECK (PRIVACY_MODE IN (0, 1)), -- 0: Visible, 1: Blur
                       CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. ACCOUNTS (Actualizada HU-04)
CREATE TABLE ACCOUNTS (
                          ID NUMBER PRIMARY KEY,
                          USER_ID NUMBER NOT NULL,
                          NAME VARCHAR2(100) NOT NULL,
                          TYPE VARCHAR2(20) NOT NULL CHECK (TYPE IN ('DEBITO', 'CREDITO', 'EFECTIVO')),
    -- Nueva columna de Moneda
                          CURRENCY VARCHAR2(3) DEFAULT 'PEN' NOT NULL CHECK (CURRENCY IN ('PEN', 'USD')),
                          BANK_NAME VARCHAR2(100),
                          INITIAL_BALANCE NUMBER(12, 2) DEFAULT 0.00 NOT NULL,
                          CREDIT_LIMIT NUMBER(12, 2) NULL,
                          CLOSING_DATE NUMBER(2),
                          PAYMENT_DATE NUMBER(2),
                          IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0, 1))
);


-- 3. CATEGORIES (Actualizada HU-09)
-- Se mantiene igual, MANAGEMENT_TYPE cubre 'PLANIFICADO_MENSUAL' vs 'DIA_A_DIA'
CREATE TABLE CATEGORIES (
                            ID NUMBER PRIMARY KEY,
                            USER_ID NUMBER NOT NULL,
                            NAME VARCHAR2(100) NOT NULL,
                            TYPE VARCHAR2(10) NOT NULL CHECK (TYPE IN ('INGRESO', 'GASTO')),
                            MANAGEMENT_TYPE VARCHAR2(20) NOT NULL CHECK (MANAGEMENT_TYPE IN ('PLANIFICADO_MENSUAL', 'DIA_A_DIA'))
);

-- 4. BUDGETS
CREATE TABLE BUDGETS (
                         ID NUMBER PRIMARY KEY,
                         USER_ID NUMBER NOT NULL,
                         CATEGORY_ID NUMBER NOT NULL,
                         AMOUNT NUMBER(12, 2) NOT NULL,
                         MONTH NUMBER(2) NOT NULL,
                         YEAR NUMBER(4) NOT NULL
);

-- 5. TAGS (Nueva HU-06)
CREATE TABLE TAGS (
                      ID NUMBER PRIMARY KEY,
                      USER_ID NUMBER NOT NULL,
                      NAME VARCHAR2(50) NOT NULL,
                      COLOR VARCHAR2(7) -- Hex code opcional para UI (ej: #FF5733)
);

-- 6. TRANSACTIONS (Actualizada HU-08)
CREATE TABLE TRANSACTIONS (
                              ID NUMBER PRIMARY KEY,
                              USER_ID NUMBER NOT NULL,
                              ACCOUNT_ID NUMBER NOT NULL,
                              CATEGORY_ID NUMBER NULL,
                              TYPE VARCHAR2(20) NOT NULL CHECK (TYPE IN ('INGRESO', 'GASTO', 'TRANSFERENCIA')),
                              AMOUNT NUMBER(12, 2) NOT NULL,
                              DESCRIPTION VARCHAR2(4000),
                              TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- Campos para Transferencias (HU-08)
    DESTINATION_ACCOUNT_ID NUMBER NULL,
    TARGET_AMOUNT NUMBER(12, 2) NULL, -- Cuánto llegó a la cuenta destino (si hay cambio de moneda)
    EXCHANGE_RATE NUMBER(10, 4) NULL  -- El tipo de cambio usado (opcional, informativo)
);

-- 7. TRANSACTION_TAGS (Tabla pivote para HU-06)
CREATE TABLE TRANSACTION_TAGS (
                                  TRANSACTION_ID NUMBER NOT NULL,
                                  TAG_ID NUMBER NOT NULL,
                                  PRIMARY KEY (TRANSACTION_ID, TAG_ID)
);

-- 8. RECURRING_TRANSACTIONS (Nueva HU-07)
-- Plantillas para generar transacciones automáticas
CREATE TABLE RECURRING_TRANSACTIONS (
                                        ID NUMBER PRIMARY KEY,
                                        USER_ID NUMBER NOT NULL,
                                        ACCOUNT_ID NUMBER NOT NULL, -- Cuenta por defecto
                                        CATEGORY_ID NUMBER NULL,
                                        TYPE VARCHAR2(20) NOT NULL,
                                        AMOUNT NUMBER(12, 2) NOT NULL,
                                        DESCRIPTION VARCHAR2(4000),

    -- Configuración de recurrencia
    FREQUENCY VARCHAR2(20) NOT NULL CHECK (FREQUENCY IN ('DIARIO', 'SEMANAL', 'MENSUAL', 'ANUAL')),
    START_DATE DATE NOT NULL,
    NEXT_EXECUTION_DATE DATE NOT NULL, -- El backend actualizará esto tras cada ejecución
    END_DATE DATE NULL, -- Opcional, si tiene fin
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0, 1))
);

-- 9. EXTERNAL_DEBTS (HU-17, HU-18)
CREATE TABLE EXTERNAL_DEBTS (
                                ID NUMBER PRIMARY KEY,
                                USER_ID NUMBER NOT NULL,
                                NAME VARCHAR2(150) NOT NULL,
                                CREDITOR VARCHAR2(100), -- A quién le debo (o quién me debe)
                                CURRENCY VARCHAR2(3) DEFAULT 'PEN' NOT NULL CHECK (CURRENCY IN ('PEN', 'USD')), -- Nueva: Deudas pueden ser en dólares
                                TOTAL_AMOUNT NUMBER(12, 2) NOT NULL,
                                CURRENT_BALANCE NUMBER(12, 2) NOT NULL
);

-- 10. SAVINGS_GOALS (HU-11)
CREATE TABLE SAVINGS_GOALS (
                               ID NUMBER PRIMARY KEY,
                               USER_ID NUMBER NOT NULL,
                               NAME VARCHAR2(150) NOT NULL,
                               CURRENCY VARCHAR2(3) DEFAULT 'PEN' NOT NULL CHECK (CURRENCY IN ('PEN', 'USD')), -- Nueva: Metas en dólares
                               TARGET_AMOUNT NUMBER(12, 2),
                               CURRENT_AMOUNT NUMBER(12, 2) DEFAULT 0.00 NOT NULL
);

-- 11. NOTIFICATIONS (HU-15, HU-16)
CREATE TABLE NOTIFICATIONS (
                               ID NUMBER PRIMARY KEY,
                               USER_ID NUMBER NOT NULL,
                               TYPE VARCHAR2(50) NOT NULL, -- Ej: 'VENCIMIENTO_TARJETA', 'PRESUPUESTO_EXCEDIDO'
                               MESSAGE VARCHAR2(255) NOT NULL,
                               IS_READ NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_READ IN (0, 1)),
                               CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ======================================================================
-- 4. CREACIÓN DE FOREIGN KEYS (Integridad Referencial)
-- ======================================================================

-- FKs Principales
ALTER TABLE ACCOUNTS ADD CONSTRAINT FK_ACC_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
ALTER TABLE CATEGORIES ADD CONSTRAINT FK_CAT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
ALTER TABLE BUDGETS ADD CONSTRAINT FK_BUD_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
ALTER TABLE BUDGETS ADD CONSTRAINT FK_BUD_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID) ON DELETE CASCADE;

-- FKs Transacciones
ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRX_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRX_ACC FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID);
ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRX_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID);
ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRX_DEST FOREIGN KEY (DESTINATION_ACCOUNT_ID) REFERENCES ACCOUNTS (ID);

-- FKs Etiquetas
ALTER TABLE TAGS ADD CONSTRAINT FK_TAG_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
ALTER TABLE TRANSACTION_TAGS ADD CONSTRAINT FK_TT_TRX FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS (ID) ON DELETE CASCADE;
ALTER TABLE TRANSACTION_TAGS ADD CONSTRAINT FK_TT_TAG FOREIGN KEY (TAG_ID) REFERENCES TAGS (ID) ON DELETE CASCADE;

-- FKs Recurrentes
ALTER TABLE RECURRING_TRANSACTIONS ADD CONSTRAINT FK_REC_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
ALTER TABLE RECURRING_TRANSACTIONS ADD CONSTRAINT FK_REC_ACC FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID);
ALTER TABLE RECURRING_TRANSACTIONS ADD CONSTRAINT FK_REC_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID);

-- FKs Otros
ALTER TABLE EXTERNAL_DEBTS ADD CONSTRAINT FK_EXT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
ALTER TABLE SAVINGS_GOALS ADD CONSTRAINT FK_SVG_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
ALTER TABLE NOTIFICATIONS ADD CONSTRAINT FK_NOT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;

COMMIT;

SELECT 'Base de Datos FINANCEDB V2 desplegada correctamente.' AS STATUS FROM DUAL;

CREATE SEQUENCE BIL_ID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 2. TABLA: SERVICE_BILLS
CREATE TABLE SERVICE_BILLS (
                               ID NUMBER PRIMARY KEY,
                               USER_ID NUMBER NOT NULL,
                               CATEGORY_ID NUMBER NOT NULL,

    -- Datos del Recibo
                               NAME VARCHAR2(150) NOT NULL,
                               COMPANY VARCHAR2(100),
                               SERVICE_CODE VARCHAR2(50),   -- Suministro/Contrato

    -- Soporte Multi-moneda (VITAL para HU-04/HU-05)
                               CURRENCY VARCHAR2(3) DEFAULT 'PEN' NOT NULL CHECK (CURRENCY IN ('PEN', 'USD')),
                               AMOUNT NUMBER(12, 2) NOT NULL,
                               FREQUENCY VARCHAR2(20),
                               DUE_DATE DATE NOT NULL,

    -- Estado controlado
                               STATUS VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL CHECK (STATUS IN ('PENDIENTE', 'PAGADO', 'VENCIDO')),

    -- AUDITORÍA DE PAGO (El eslabón perdido del Backend)
    -- Cuando se pague, aquí guardaremos el ID de la transacción generada.
    -- Esto permite ir del Recibo al Gasto y viceversa.
                               TRANSACTION_ID NUMBER UNIQUE,

                               CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT chk_bill_frequency CHECK (FREQUENCY IN ('UNICO', 'MENSUAL', 'BIMENSUAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL')),
    -- Relaciones (Integridad Referencial)
                               CONSTRAINT FK_BILL_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
                               CONSTRAINT FK_BILL_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID),
                               CONSTRAINT FK_BILL_TRX FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS (ID) -- Sin Cascade, historial protegido
);

-- Índices Recomendados para Rendimiento (Queries de Dashboard)
CREATE INDEX IDX_BILL_USER_STATUS ON SERVICE_BILLS(USER_ID, STATUS);
CREATE INDEX IDX_BILL_DUE_DATE ON SERVICE_BILLS(DUE_DATE);

COMMIT;

